# Токен вашего Telegram бота (получите у @BotFather)
telegram_token: ""

# Ключ API OpenAI (получите на https://platform.openai.com/api-keys)
openai_api_key: ""

# Базовый URL API OpenAI (оставьте null для использования по умолчанию или укажите свой URL)
openai_api_base: null  # оставьте null для использования стандартного API или укажите свой базовый URL

# Список разрешенных пользователей Telegram (если пустой, бот доступен всем)
# Передайте строку с именем пользователя для разрешения и/или ID пользователей как положительные целые числа и/или ID каналов как отрицательные целые числа
allowed_telegram_usernames: []  # если пустой, бот доступен всем. передайте строку с именем пользователя для разрешения и/или ID пользователей как положительные целые числа и/или ID каналов как отрицательные целые числа

# Таймаут нового диалога (в секундах)
new_dialog_timeout: 600  # новый диалог начинается после таймаута (в секундах)

# Количество генерируемых изображений
return_n_generated_images: 1

# Количество режимов чата на странице
n_chat_modes_per_page: 5

# Размер изображения для генерации изображений. Сгенерированные изображения могут иметь размер 256x256, 512x512 или 1024x1024 пикселей. Меньшие размеры генерируются быстрее.
image_size: "512x512" # размер изображения для генерации изображений. Сгенерированные изображения могут иметь размер 256x256, 512x512 или 1024x1024 пикселей. Меньшие размеры генерируются быстрее.

# Включить потоковую передачу сообщений
enable_message_streaming: true  # если установлено, сообщения будут показываться пользователю слово за словом

# Цены
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
